title: "Supreet Gulavani"
email: "sgsupreetgulavani@gmail.com"
description: >- 
  Personal website and blog of Supreet Gulavani.
baseurl: "" 
url: "https://supreetgulavani.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
